#! /bin/sh

sxhkd &

xrandr --dpi 144

bspc monitor eDP-1 -d I II III IV V VI VII VIII IX X

bspc config border_width         0
bspc config window_gap           8

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true

polybar bar & 

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

bspc config pointer_modifier mod4
bspc config pointer_action2 move
bspc config pointer_action1 resize_corner
bspc config pointer_action3 resize_side

compton --config ~/.config/compton.conf &
setxkbmap -option compose:menu

xrdb -merge ~/.Xresources

feh --randomize --bg-fill ~/Wallpapers/Desktop
